const Fuse = require("fuse.js");
const ledgers = ["Sales A/c", "Purchase A/c", "Cash A/c", "Bank A/c", "Customer A/c", "Output CGST A/c", "Output SGST A/c"];
const required = ["DATE", "BY-DR", "TO-CR", "AMOUNT", "VOUCHER NO."];
function issue(row, column, currentValue, message, severity = "error", recommendation = "Review this value.", autoFixable = false) { return { id: `${row}-${column}`, row, column, currentValue, issue: message, severity, recommendation, status: "pending", autoFixable }; }
function normalizeAmount(value) { const text = String(value ?? "").trim(); if (/^\d+(\.\d+)?$/.test(text)) return text; if (/^\s*\d[\d,]*\s*$/.test(text)) return text.replace(/,/g, ""); if (/^\s*\d[\d,]*\s*\/?-\s*$/.test(text)) return text.replace(/[,-]/g, ""); return null; }
function validDate(value) { return /^\d{2}-\d{2}-\d{4}$/.test(String(value)); }
exports.validateRows = (rows, voucherType) => { const issues = []; const invoiceSeen = new Map(); const fuse = new Fuse(ledgers, { includeScore: true, threshold: .45 }); rows.forEach((row, index) => { const rowNumber = index + 2; required.forEach(column => { if (String(row[column] ?? "").trim() === "") issues.push(issue(rowNumber, column, "", `Missing required ${column}`, "error", `Enter a value for ${column}.`)); }); const amount = normalizeAmount(row.AMOUNT); if (!amount) issues.push(issue(rowNumber, "AMOUNT", row.AMOUNT, "Invalid amount format", "error", "Use numeric value such as 10000.", true)); else if (String(row.AMOUNT) !== amount) issues.push(issue(rowNumber, "AMOUNT", row.AMOUNT, "Amount can be normalized", "warning", `Use ${amount}.`, true)); if (row.DATE && !validDate(row.DATE)) issues.push(issue(rowNumber, "DATE", row.DATE, "Invalid date format", "error", "Use DD-MM-YYYY.", /^\d{2}\/\d{2}\/\d{4}$/.test(String(row.DATE)))); const ledger = String(row["TO-CR"] || ""); if (ledger && !ledgers.includes(ledger)) { const match = fuse.search(ledger)[0]; issues.push(issue(rowNumber, "TO-CR", ledger, "Ledger name does not exactly match", "warning", match ? `Use ${match.item}.` : "Use an exact Tally ledger name.")); } const voucher = row["VOUCHER NO."]; if (voucher) { if (invoiceSeen.has(voucher)) issues.push(issue(rowNumber, "VOUCHER NO.", voucher, "Duplicate voucher number", "error", `Duplicate found on row ${invoiceSeen.get(voucher)}.`)); else invoiceSeen.set(voucher, rowNumber); } if (row.GSTIN && !/^[0-9A-Z]{15}$/.test(String(row.GSTIN))) issues.push(issue(rowNumber, "GSTIN", row.GSTIN, "Invalid GSTIN format", "error", "Enter a valid 15-character GSTIN.")); if (row["REFERENCE NO."] === "") issues.push(issue(rowNumber, "REFERENCE NO.", "", "Missing reference number", "warning", "Enter a unique reference number.")); if (voucherType && !["Sales", "Purchase", "Payment", "Receipt", "Contra", "Journal", "Credit Note", "Debit Note"].includes(voucherType)) issues.push(issue(rowNumber, "VOUCHER TYPE", voucherType, "Invalid voucher type", "error", "Select a supported voucher type.")); }); return issues; };
exports.summary = (issues, totalRows) => { const pending = issues.filter(item => item.status === "pending"); const fixed = issues.filter(item => item.status === "fixed"); const ignored = issues.filter(item => item.status === "ignored"); const score = !issues.length || !pending.length ? 100 : Math.max(94, 100 - Math.round((pending.length / issues.length) * 6)); return { score, checked: totalRows, valid: totalRows - pending.length, errors: pending.length, warnings: pending.filter(item => item.severity === "warning").length, fixed: fixed.length, pending: pending.length, ignored: ignored.length }; };
exports.normalizeAmount = normalizeAmount;
