const Upload = require("../models/Upload"); const Validation = require("../models/Validation"); const ValidationReport = require("../models/ValidationReport"); const { validateRows, summary } = require("../services/validationService"); const { applySafeFixes } = require("../services/autoFixService");
const own = (validation, user) => validation && (user.role === "admin" || String(validation.user) === String(user._id));
async function report(validation) { const stats = summary(validation.issues, validation.checked); validation.score = stats.score; validation.valid = stats.valid; validation.errors = stats.errors; validation.warnings = stats.warnings; validation.status = stats.errors ? "needs_review" : "validated"; return stats; }
exports.validate = async (req, res, next) => { try { const upload = await Upload.findOne({ _id: req.params.uploadId, user: req.user._id }); if (!upload) return res.status(404).json({ success: false, message: "Upload not found", code: "NOT_FOUND" }); const issues = validateRows(upload.dataRows, upload.voucherType); const validation = await Validation.create({ user: req.user._id, upload: upload._id, issues, checked: upload.rows }); const stats = await report(validation); await validation.save(); await ValidationReport.create({ user: req.user._id, validation: validation._id, fileName: upload.originalName, ...stats, status: validation.status }); upload.errors = stats.errors; upload.warnings = stats.warnings; upload.status = "validated"; await upload.save(); res.json({ success: true, validationId: validation._id, ...stats, issues: validation.issues }); } catch (e) { next(e); } };
exports.get = async (req, res, next) => { try { const validation = await Validation.findOne({ _id: req.params.validationId, user: req.user._id }); if (!validation) return res.status(404).json({ success: false, message: "Validation not found", code: "NOT_FOUND" }); res.json({ success: true, validation }); } catch (e) { next(e); } };
exports.autoFix = async (req, res, next) => { try { const validation = await Validation.findOne({ _id: req.params.validationId, user: req.user._id }); if (!validation) return res.status(404).json({ success: false, message: "Validation not found", code: "NOT_FOUND" }); validation.issues = applySafeFixes(validation.issues); const stats = await report(validation); await validation.save(); res.json({ success: true, ...stats, issues: validation.issues }); } catch (e) { next(e); } };
exports.fixIssue = async (req, res, next) => { try { const validation = await Validation.findOne({ _id: req.params.validationId, user: req.user._id }); const item = validation?.issues.find(issue => issue.id === req.params.issueId); if (!item) return res.status(404).json({ success: false, message: "Issue not found", code: "NOT_FOUND" }); item.status = "fixed"; if (item.column === "AMOUNT") item.currentValue = String(item.currentValue).replace(/[₹,\s/-]/g, ""); if (item.column === "DATE") item.currentValue = String(item.currentValue).replace(/\//g, "-"); const stats = await report(validation); await validation.save(); res.json({ success: true, updatedIssue: item, summary: stats }); } catch (e) { next(e); } };
exports.apply = async (req, res, next) => { req.body = { ...req.body, action: "apply" }; return exports.fixIssue(req, res, next); };
exports.ignore = async (req, res, next) => { try { const validation = await Validation.findOne({ _id: req.params.validationId, user: req.user._id }); const item = validation?.issues.find(issue => issue.id === req.params.issueId); if (!item) return res.status(404).json({ success: false, message: "Issue not found", code: "NOT_FOUND" }); item.status = "ignored"; const stats = await report(validation); await validation.save(); res.json({ success: true, updatedIssue: item, summary: stats }); } catch (e) { next(e); } };
exports.revalidate = async (req, res, next) => { try { const validation = await Validation.findOne({ _id: req.params.validationId, user: req.user._id }); if (!validation) return res.status(404).json({ success: false, message: "Validation not found", code: "NOT_FOUND" }); const stats = await report(validation); await validation.save(); await ValidationReport.create({ user: req.user._id, validation: validation._id, ...stats, status: validation.status }); res.json({ success: true, ...stats, status: validation.status, issues: validation.issues }); } catch (e) { next(e); } };
